# Zillow
- For the following, iterate through the steps you would take to create functions: Write the code to do the following in a jupyter notebook, test it, convert to functions, then create the file to house those functions.

- You will have a zillow.ipynb file and a helper file for each section in the pipeline.

## Acquire and Summarize

1. Acquire data from the cloud database.
- You will want to end with a single dataframe. Include the logerror field and all other fields related to the properties that are available. You will end up using all the tables in the database.

- Be sure to do the correct join (inner, outer, etc.). We do not want to eliminate properties purely because they may have a null value for airconditioningtypeid. - Only include properties with a transaction in 2017, and include only the last transaction for each property (so no duplicate property ID's), along with zestimate error and date of transaction. (Hint: read the docs for the .duplicated method) - Only include properties that have a latitude and longitude value.

2. Summarize your data (summary stats, info, dtypes, shape, distributions, value_counts, etc.)


3. Write a function that takes in a dataframe of observations and attributes and returns a dataframe where each row is an atttribute name, the first column is the number of rows with missing values for that attribute, and the second column is percent of total rows that have missing values for that attribute. Run the function and document takeaways from this on how you want to handle missing values.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import env

In [2]:
sql_query = '''
    select * 
    from properties_2017
    left join airconditioningtype using(airconditioningtypeid)
    left join architecturalstyletype using(architecturalstyletypeid)
    left join buildingclasstype using(buildingclasstypeid)
    left join heatingorsystemtype using (heatingorsystemtypeid)
    left join propertylandusetype using(propertylandusetypeid)
    left join storytype using(storytypeid)
    left join typeconstructiontype using(typeconstructiontypeid)
    left join unique_properties using(parcelid);
    '''

In [3]:
def get_zillow_data():
    '''
    This function uses a SQL query 
    and get_connection function from the envy.py file
    to create df of zillow data
    '''    
    df = pd.read_sql(sql_query, env.get_connection('zillow'))
    
    return df

In [4]:
#assign variable to our function
df = get_zillow_data()

#take a look
df.head()

,parcelid,typeconstructiontypeid,storytypeid,propertylandusetypeid,heatingorsystemtypeid,buildingclasstypeid,architecturalstyletypeid,airconditioningtypeid,id,basementsqft,...,taxdelinquencyflag,taxdelinquencyyear,censustractandblock,airconditioningdesc,architecturalstyledesc,buildingclassdesc,heatingorsystemdesc,propertylandusedesc,storydesc,typeconstructiondesc
0,10754147,NaN,NaN,269.0,NaN,NaN,NaN,NaN,0,NaN,...,None,NaN,NaN,None,None,None,None,Planned Unit Development,None,None
1,10759547,NaN,NaN,261.0,NaN,NaN,NaN,NaN,1,NaN,...,None,NaN,NaN,None,None,None,None,Single Family Residential,None,None
2,10843547,NaN,NaN,47.0,NaN,5.0,NaN,NaN,2,NaN,...,None,NaN,NaN,None,None,Specialized buildings that do not fit in any o...,None,Store/Office (Mixed Use),None,None
3,10859147,NaN,NaN,47.0,NaN,3.0,NaN,NaN,3,NaN,...,None,NaN,NaN,None,None,Buildings having exterior walls built of a non...,None,Store/Office (Mixed Use),None,None
4,10879947,NaN,NaN,31.0,NaN,4.0,NaN,NaN,4,NaN,...,None,NaN,NaN,None,None,Buildings having wood or wood and steel frames,None,Commercial/Office/Residential Mixed Used,None,None

In [5]:
df.to_csv('zillow_joined.csv')

In [6]:
#descriptive stats for our numeric columns
df.describe().T

,count,mean,std,min,25%,50%,75%,max
parcelid,2985217.0,1.332586e+07,7.909966e+06,1.071172e+07,1.164371e+07,1.254509e+07,1.409712e+07,1.696019e+08
typeconstructiontypeid,6746.0,5.999555e+00,3.840787e-01,4.000000e+00,6.000000e+00,6.000000e+00,6.000000e+00,1.300000e+01
storytypeid,1623.0,7.000000e+00,0.000000e+00,7.000000e+00,7.000000e+00,7.000000e+00,7.000000e+00,7.000000e+00
propertylandusetypeid,2982285.0,2.600508e+02,1.593121e+01,3.100000e+01,2.610000e+02,2.610000e+02,2.610000e+02,2.790000e+02
heatingorsystemtypeid,1869164.0,4.083750e+00,3.286780e+00,1.000000e+00,2.000000e+00,2.000000e+00,7.000000e+00,2.400000e+01
buildingclasstypeid,12731.0,3.734742e+00,5.003709e-01,1.000000e+00,3.000000e+00,4.000000e+00,4.000000e+00,5.000000e+00
architecturalstyletypeid,6061.0,7.202607e+00,2.436290e+00,2.000000e+00,7.000000e+00,7.000000e+00,7.000000e+00,2.700000e+01
airconditioningtypeid,815362.0,1.945723e+00,3.160507e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.300000e+01
id,2985217.0,1.492608e+06,8.617581e+05,0.000000e+00,7.463040e+05,1.492608e+06,2.238912e+06,2.985216e+06
basementsqft,1627.0,6.472207e+02,5.387871e+02,2.000000e+01,2.720000e+02,5.350000e+02,8.475000e+02,8.516000e+03
bathroomcnt,2982260.0,2.216196e+00,1.078250e+00,0.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,3.200000e+01
bedroomcnt,2982272.0,3.093362e+00,1.271569e+00,0.000000e+00,2.000000e+00,3.000000e+00,4.000000e+00,2.500000e+01
buildingqualitytypeid,1941395.0,6.280822e+00,1.729923e+00,1.000000e+00,5.000000e+00,6.000000e+00,8.000000e+00,1.200000e+01
calculatedbathnbr,2868061.0,2.303826e+00,1.003243e+00,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,3.200000e+01
decktypeid,17379.0,6.600000e+01,0.000000e+00,6.600000e+01,6.600000e+01,6.600000e+01,6.600000e+01,6.600000e+01
finishedfloor1squarefeet,203758.0,1.379780e+03,6.344228e+02,1.000000e+00,1.010000e+03,1.281000e+03,1.615000e+03,3.130300e+04
calculatedfinishedsquarefeet,2940120.0,1.831455e+03,1.954198e+03,1.000000e+00,1.215000e+03,1.574000e+03,2.140000e+03,9.525760e+05
finishedsquarefeet12,2720786.0,1.764045e+03,1.031383e+03,1.000000e+00,1.198000e+03,1.542000e+03,2.075000e+03,4.270790e+05
finishedsquarefeet13,7671.0,1.178917e+03,3.570936e+02,1.200000e+02,9.600000e+02,1.296000e+03,1.440000e+03,2.688000e+03
finishedsquarefeet15,190185.0,2.754869e+03,5.999380e+03,1.120000e+02,1.696000e+03,2.173000e+03,2.975000e+03,8.202420e+05
finishedsquarefeet50,203758.0,1.392029e+03,6.823239e+02,3.000000e+00,1.012000e+03,1.284000e+03,1.619000e+03,4.190600e+04
finishedsquarefeet6,21482.0,2.427555e+03,7.786185e+03,1.170000e+02,1.072000e+03,2.008000e+03,3.411000e+03,9.525760e+05
fips,2982285.0,6.048053e+03,2.024082e+01,6.037000e+03,6.037000e+03,6.037000e+03,6.059000e+03,6.111000e+03
fireplacecnt,313124.0,1.168959e+00,4.618549e-01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,9.000000e+00
fullbathcnt,2868061.0,2.248089e+00,9.929959e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,3.200000e+01
garagecarcnt,891008.0,1.826581e+00,6.089337e-01,0.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.500000e+01
garagetotalsqft,891008.0,3.831562e+02,2.462194e+02,0.000000e+00,3.120000e+02,4.410000e+02,4.940000e+02,7.749000e+03
hashottuborspa,50062.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
latitude,2982285.0,3.400131e+07,2.435157e+05,3.332439e+07,3.382740e+07,3.400807e+07,3.416186e+07,3.481965e+07
longitude,2982285.0,-1.182017e+08,3.455918e+05,-1.194758e+08,-1.183929e+08,-1.181721e+08,-1.179489e+08,-1.175543e+08
lotsizesquarefeet,2712511.0,2.260376e+04,2.499836e+05,1.000000e+02,5.683000e+03,7.000000e+03,9.893000e+03,3.710005e+08
poolcnt,539632.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
poolsizesum,27958.0,5.197154e+02,1.913259e+02,1.900000e+01,4.300000e+02,4.950000e+02,5.940000e+02,1.741000e+04
pooltypeid10,17006.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
pooltypeid2,33056.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
pooltypeid7,505895.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
rawcensustractandblock,2982285.0,6.048367e+07,2.008914e+05,6.037101e+07,6.037400e+07,6.037571e+07,6.059042e+07,6.111009e+07
regionidcity,2923089.0,3.498766e+04,5.070968e+04,3.491000e+03,1.244700e+04,2.521800e+04,4.545700e+04,3.965560e+05
regionidcounty,2982285.0,2.569085e+03,7.886840e+02,1.286000e+03,1.286000e+03,3.101000e+03,3.101000e+03,3.101000e+03
regionidneighborhood,1156741.0,1.935387e+05,1.657253e+05,6.952000e+03,4.673600e+04,1.189200e+05,2.748000e+05,7.641670e+05
regionidzip,2972503.0,9.655329e+04,3.680815e+03,9.598200e+04,9.618000e+04,9.637700e+04,9.697400e+04,3.996750e+05
roomcnt,2982248.0,1.474357e+00,2.839869e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.600000e+01
threequarterbathnbr,316357.0,1.010611e+00,1.206024e-01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,7.000000e+00
unitcnt,1981042.0,1.180303e+00,2.486949e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,9.970000e+02
yardbuildingsqft17,81588.0,3.215416e+02,2.368848e+02,1.000000e+01,1.900000e+02,2.700000e+02,3.900000e+02,7.983000e+03
yardbuildingsqft26,2646.0,2.783655e+02,3.697844e+02,1.000000e+01,9.600000e+01,1.680000e+02,3.200000e+02,6.141000e+03
yearbuilt,2937384.0,1.964438e+03,2.364428e+01,1.801000e+03,1.950000e+03,1.963000e+03,1.981000e+03,2.016000e+03
numberofstories,685676.0,1.400956e+00,5.390565e-01,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,4.100000e+01
fireplaceflag,5163.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
structuretaxvaluedollarcnt,2938753.0,1.781429e+05,4.600503e+05,1.000000e+00,7.766600e+04,1.270660e+05,2.040000e+05,2.553212e+08
taxvaluedollarcnt,2950951.0,4.435279e+05,8.163366e+05,1.000000e+00,1.882200e+05,3.211610e+05,5.140720e+05,3.196225e+08
assessmentyear,2982284.0,2.015998e+03,6.039949e-02,2.000000e+03,2.016000e+03,2.016000e+03,2.016000e+03,2.016000e+03
landtaxvaluedollarcnt,2925291.0,2.684558e+05,4.865097e+05,1.000000e+00,7.970000e+04,1.766190e+05,3.261000e+05,9.401108e+07
taxamount,2962465.0,5.408949e+03,9.675567e+03,2.400000e-01,2.468620e+03,4.007620e+03,6.230500e+03,3.823176e+06
taxdelinquencyyear,56517.0,1.389170e+01,2.562172e+00,0.000000e+00,1.400000e+01,1.400000e+01,1.500000e+01,9.900000e+01
censustractandblock,2910232.0,6.048434e+13,3.249133e+11,-1.000000e+00,6.037400e+13,6.037572e+13,6.059042e+13,4.830301e+14

In [7]:
#how many rows and columns do we have
print(f'rows: {df.shape[0]}')
print(f'co1umns: {df.shape[1]}')

rows: 2985217
co1umns: 66

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2985217 entries, 0 to 2985216
Data columns (total 66 columns):
 #   Column                        Dtype
---  ------                        -----
 0   parcelid                      int64
 1   typeconstructiontypeid        float64
 2   storytypeid                   float64
 3   propertylandusetypeid         float64
 4   heatingorsystemtypeid         float64
 5   buildingclasstypeid           float64
 6   architecturalstyletypeid      float64
 7   airconditioningtypeid         float64
 8   id                            int64
 9   basementsqft                  float64
 10  bathroomcnt                   float64
 11  bedroomcnt                    float64
 12  buildingqualitytypeid         float64
 13  calculatedbathnbr             float64
 14  decktypeid                    float64
 15  finishedfloor1squarefeet      float64
 16  calculatedfinishedsquarefeet  float64
 17  finishedsquarefeet12          float64
 18  finishedsquarefeet13          float64
 19  finishedsquarefeet15          float64
 20  finishedsquarefeet50          float64
 21  finishedsquarefeet6           float64
 22  fips                          float64
 23  fireplacecnt                  float64
 24  fullbathcnt                   float64
 25  garagecarcnt                  float64
 26  garagetotalsqft               float64
 27  hashottuborspa                float64
 28  latitude                      float64
 29  longitude                     float64
 30  lotsizesquarefeet             float64
 31  poolcnt                       float64
 32  poolsizesum                   float64
 33  pooltypeid10                  float64
 34  pooltypeid2                   float64
 35  pooltypeid7                   float64
 36  propertycountylandusecode     object
 37  propertyzoningdesc            object
 38  rawcensustractandblock        float64
 39  regionidcity                  float64
 40  regionidcounty                float64
 41  regionidneighborhood          float64
 42  regionidzip                   float64
 43  roomcnt                       float64
 44  threequarterbathnbr           float64
 45  unitcnt                       float64
 46  yardbuildingsqft17            float64
 47  yardbuildingsqft26            float64
 48  yearbuilt                     float64
 49  numberofstories               float64
 50  fireplaceflag                 float64
 51  structuretaxvaluedollarcnt    float64
 52  taxvaluedollarcnt             float64
 53  assessmentyear                float64
 54  landtaxvaluedollarcnt         float64
 55  taxamount                     float64
 56  taxdelinquencyflag            object
 57  taxdelinquencyyear            float64
 58  censustractandblock           float64
 59  airconditioningdesc           object
 60  architecturalstyledesc        object
 61  buildingclassdesc             object
 62  heatingorsystemdesc           object
 63  propertylandusedesc           object
 64  storydesc                     object
 65  typeconstructiondesc          object
dtypes: float64(54), int64(2), object(10)
memory usage: 1.5+ GB

In [12]:
def missing_values(df):
    num_rows = len(df)
    missing = df.isnull().sum()
    percent_missing = (missing / num_rows) * 100
    result = pd.concat([missing, percent_missing], axis=1)
    result.columns = ['num_rows_missing', 'pct_rows_missing']
    result.index.name = 'feature'
    return result.sort_values(by='pct_rows_missing', ascending=False)

In [17]:
mis_val = missing_values(df)

In [24]:
mis_val

                       num_rows_missing  pct_rows_missing
feature
storytypeid                     2983594         99.945632
storydesc                       2983594         99.945632
basementsqft                    2983590         99.945498
yardbuildingsqft26              2982571         99.911363
fireplaceflag                   2980054         99.827048
...                                 ...               ...
fips                               2932          0.098217
propertylandusedesc                2932          0.098217
propertylandusetypeid              2932          0.098217
id                                    0          0.000000
parcelid                              0          0.000000

[66 rows x 2 columns]

# Prepare

1. Remove any properties that are likely to be something other than single unit properties. (e.g. no duplexes, no land/lot, ...). There are multiple ways to estimate that a property is a single unit, and there is not a single "right" answer.

2. Create a function that will drop rows or columns based on the percent of values that are missing: handle_missing_values(df, prop_required_column, prop_required_row).

 - The input:
    - A dataframe
    - A number between 0 and 1 that represents the proportion, for each column, of rows with non-missing values required to keep the column. i.e. if prop_required_column = .6, then you are requiring a column to have at least 60% of values not-NA (no more than 40% missing).
    - A number between 0 and 1 that represents the proportion, for each row, of columns/variables with non-missing values required to keep the row. For example, if prop_required_row = .75, then you are requiring a row to have at least 75% of variables with a non-missing value (no more that 25% missing).
- The output:
    - The dataframe with the columns and rows dropped as indicated. Be sure to drop the columns prior to the rows in your function.
- hint:
    - Look up the dropna documentation.
    - You will want to compute a threshold from your input values (prop_required) and total number of rows or columns.
3. Encapsulate your work inside of functions in a wrangle_zillow.py module.

In [39]:
single_fam_df  = df[df['propertylandusetypeid'] == (261 or 279)]

In [41]:
single_fam_df.shape

(2152863, 67)

In [46]:
single_fam_df.isnull().sum()

Unnamed: 0                      0
parcelid                        0
typeconstructiontypeid    2150205
storytypeid               2151328
propertylandusetypeid           0
                           ...
buildingclassdesc         2152862
heatingorsystemdesc        728010
propertylandusedesc             0
storydesc                 2151328
typeconstructiondesc      2150205
Length: 67, dtype: int64

In [47]:
def handle_missing_values(df, prop_required_column, prop_required_row):
    '''
    The input:
    - A dataframe
    - A number between 0 and 1 that represents the proportion, for each column, 
    of rows with non-missing values required to keep the column. 
    - A number between 0 and 1 that represents the proportion, for each row, 
    of columns/variables with non-missing values required to keep the row. 
    
    The output:
    - The dataframe with the columns and rows dropped as indicated.
    '''
    # drop columns that do not meet prop_required_column
    df = df.dropna(thresh=int(prop_required_column*len(df)), axis=1)

    # drop rows that do not meet prop_required_row
    df = df.dropna(thresh=int(prop_required_row*len(df.columns)), axis=0)

    return df